# Site settings
title: FLO Airride Mfg.
email: mphillips.slamd@gmail.com
description: > #The future of Airride is upon us. FLO is proud and ecstatic to be
bringing the absolute best in Airride suspension components. New products and
builds launching Fall, 2016. Be on the lookout for the lowest. FLO Airride Mfg.
2016.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://floairride.com" # the base hostname & protocol for your site
twitter_username:
github_username:  flo-airride-mfg

# Build settings
markdown: kramdown
