
title: FLO Airride Mfg.
email: mikea@floairride.com
description: > # this means to ignore newlines until "baseurl:"
          Consumed by air suspension, FLO Airride Co-Founders Mike Alexander and Eric Conner teamed up to breathe new life into the air ride community, taking their collective passion for creating works of art to a whole new level. FLO Airride Mfg. will focus on high-quality air supply products that perform as well as they look, getting back to the basics and taking a designer's artful eye to every single component.
baseurl: ""
url: "floairride.com"
twitter_username:
github_username:

markdown: kramdown
