# Site settings
title: FLO Airride Mfg.
email: mphillips.slamd@gmail.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://floairride.com" # the base hostname & protocol for your site
twitter_username:
github_username:  flo-airride-mfg

# Build settings
markdown: kramdown
